### ISSUE TITLE
Suggestion: more dolls and automated barrels

### ISSUE THREAD

**Issue by Yusunoha** [blay09/ExCompressum#104]
a problem you usually face with skyblocks maps is not being able to properly find biomes, and thus being able to find biome specific mobs.

Compressum already adds a way to spawn animals, and Nihilo and Astris gives the player a few dolls that they can craft to spawn certain mobs through a barrel, but you're only able to summon blaze, endermen, pechs and blizz. but thermal has added a few more types of blazes, blitz and basalz, who don't have doll versions. it'd be nice if these mobs could also have doll versions of them so that you can use those to summon these mobs aswell, as their drops are also needed for some of the thermal recipes.

and so far we've had automated hammers and sieves, but no automated barrels. automated barrels could perhaps be used to use less resources to create dirt, or have an eternal inventory for water, so you don't need to have a water source ontop a barrel to create lava, and ofcourse a faster processing speed. maybe if you want to go crazy you could also perhaps use automated barrels for better summoning of mobs through barrels, where for example 1 doll could spawn 8 mobs instead of 1.

**Comment by blay09** [comment]
Closing since Thermal Expansion isn't a thing in 1.10.2 and barrels can already be automated just fine using pipes or hoppers.
