### ISSUE TITLE
Crash when placing Sieve

### ISSUE THREAD

**Issue by HelixAngler** [blay09/ExCompressum#111]
blay09, there's a problem with one of the object in your mod. Every time i placed Heavy Auto Sieve, the game always crashed. But, when i reaccesseed my saved data, the sieve was still on place and work as it was supposed to (it still crashed when I placed the block). Here's the log:

**Edit: Please use pastebin for log files instead of embedding them directly.**
http://pastebin.com/SSMFpEik

I hope you can fix this.

**Comment by mariotacke** [comment]
Experiencing the same issue with the regular Auto Sieve.

**Comment by falsidge** [comment]
It seems fine for me.
Maybe Mojang's server was down when the skin was requested and returned a blank array, which couldn't be converted to a Json object
