### ISSUE TITLE
Auto Compressor - Performance Issues

### ISSUE THREAD

**Issue by Sir-Will** [blay09/ExCompressum#118]
hey,

can you please look into this performance issue and improve it?

![](http://image.prntscr.com/image/871bfced2d5a46caa2098ab7f4d141be.png)

**Comment by blay09** [comment]
Please try build [144](http://jenkins.blay09.net/job/Ex%20Compressum/144/) and see if it works better for you.

**Comment by Sir-Will** [comment]
Seems to have fixed it, thanks!
