### ISSUE TITLE
Crash on adding newest version. 

### ISSUE THREAD

**Issue by xellosmetallum** [blay09/ExCompressum#12]
When adding the newest version of ExCompressum to Project Ozone I am getting this crash.
http://pastebin.com/9BKNY8aP

It works fine with 1.1.25

**Comment by blay09** [comment]
Weird, looks like some other mod is registering a recipe with an item stack that has no item attached to it.

Could you try if v1.1.42+ works (see http://jenkins.blay09.net/job/Ex%20Compressum/)?

**Comment by xellosmetallum** [comment]
Seems like that fixed it!
