### ISSUE TITLE
Server crashing on boot

### ISSUE THREAD

**Issue by jpearson24** [blay09/ExCompressum#121]
[http://blay09.net/eiranet/api/skins.php](http://blay09.net/eiranet/api/skins.php) currently shows [http://i.imgur.com/CeRsGlv.png](http://i.imgur.com/CeRsGlv.png)

We're getting this error on boot: [http://i.imgur.com/WXNQmce.jpg](http://i.imgur.com/WXNQmce.jpg)

**Comment by clement-bramy** [comment]
Same as #122 see my comment there.

**Comment by scroyall** [comment]
Until a fix is forthcoming, add a failing entry for blay09.net to your hosts file if you are able.

0.0.0.0 blay09.net

**Comment by clement-bramy** [comment]
Worked for me!

**Comment by darkcamo12** [comment]
runs command prompt "run as Administrator"
and use the following route add 37.59.0.98 mask 255.255.255.255 0.0.0.0

once the client computer reboots is should reset this

**Comment by blay09** [comment]
Sorry. My server died for a bit there and I thought Ex Compressum would have handled it correctly but for some reason the JSON parser disagreed. I've put a temporary fix up so you should be able to run properly again.

**Comment by blay09** [comment]
Or maybe not? Let me try

**Comment by blay09** [comment]
Okay, for real now.

**Comment by Lordicon** [comment]
Any way to add an exception so when the database can not be reached it still allows the load but sends you a message so you know there is an issue?

btw thank you it is working now

**Comment by blay09** [comment]
That was the plan all along, but I failed to prepare properly for a case like this. I'll make sure something like this never happens again though.
