### ISSUE TITLE
Game crashing on startup

### ISSUE THREAD

**Issue by Wealthyturtle** [blay09/ExCompressum#122]
Hi, I have recently been getting this crash. However, I managed to successfully startup minecraft a couple times before this crash started to occur. Ever since this crash has occurred, minecraft is unable to startup anymore.

Crash Reports:
Crash Report: [http://pastebin.com/s3289P6Q](http://pastebin.com/s3289P6Q)
Console: [http://pastebin.com/dYVKaYat](http://pastebin.com/dYVKaYat)

**Comment by clement-bramy** [comment]
I have the exact same issue.

It looks like according to the code below:
URL remoteURL = new URL("http://blay09.net/eiranet/api/skins.php");
            InputStream in = remoteURL.openStream();
            Gson gson = new Gson();
            JsonReader reader = new JsonReader(new InputStreamReader(in));
            JsonObject root = gson.fromJson(reader, JsonObject.class);

Is trying to load a file from the website (to load supporter's skins I guess).
However, the website is currently offline (Error establishing a database connection).

Hence it kinda crash the game for everyone at the moment.
Better implement a failsafe for that kind of feature..

Regards,
Clem

**Comment by Wealthyturtle** [comment]
Do you think it's possible to disable the connection?

**Comment by Wealthyturtle** [comment]
Just checked the config file, you can only disable the auto sieve's recipe. Not the actual block

**Comment by clement-bramy** [comment]
https://github.com/blay09/ExCompressum/issues/121#issuecomment-225808068 this workaround worked for me

**Comment by Wealthyturtle** [comment]
Well, this is technically for my modpack. I don't want to trouble my downloaders with this tho...

**Comment by blay09** [comment]
Sorry. My server died for a bit there and I thought Ex Compressum would have handled it correctly but for some reason the JSON parser disagreed. I've put a temporary fix up so you should be able to run properly again.

**Comment by clement-bramy** [comment]
Wealthyturtle, I am sure blay09 will implement a failsafe in the function loading the skin list, so it does not happen in the future ;)

**Comment by Wealthyturtle** [comment]
Alright, thanks for the fix :)
