### ISSUE TITLE
Auto Compressor does not finish Item Stacks

### ISSUE THREAD

**Issue by thatsIch** [blay09/ExCompressum#127]
Greetings,

when items are inserted into the inventory of the auto compressor, the insertion is not happening on already existing item stacks. The insertion happens on the first available free slot, if the to be completed stack has a higher slot index.

Example:

* Slot 0 is free
* Slot 1 has Redstone
* Redstone enters the inventory
* now Redstone is in Slot 0 and 1

Expected behaviour:

* Inventory tries to finish the existing stack first before starting a new stack

Problem scenario:

Even with filtering items, there is a chance where having only few items in the filter the compressor can jam the system, because the other items can not enter the compressor cause of lacking free inventory slot.

**Comment by blay09** [comment]
This depends on the method of input used, but should no longer occur in 1.10.2 assuming people are using the "smart" default implementation for insertion in their pipes and such.
