### ISSUE TITLE
Can only place cow bait in water

### ISSUE THREAD

**Issue by chrisbecke** [blay09/ExCompressum#129]
Apologies if this is intentional, but attempting to place cow bait in an infinity evolved skyblock map fails to do anything - seemingly unless the destination block has water.

**Comment by blay09** [comment]
Are you on the latest version?

**Comment by chrisbecke** [comment]
FTB Infinity Evolved Skyblock uses ExC 1.1.113 - so no.

**Comment by blay09** [comment]
Version 1.2.0 of FTB Infinity Evolved Skyblock uses Ex Compressum 1.1.143, you need to update.
