### ISSUE TITLE
[1.7.10_1.1.143] Can't pipe Compressed Hammers into the Auto-Compressed Hammer

### ISSUE THREAD

**Issue by DeadSix27** [blay09/ExCompressum#132]
Version: excompressum-mc1.7.10-1.1.143
I'm unable to input Compressed Diamond Hammers with any Pipe into the Auto Compressed Hammer

**Comment by blay09** [comment]
1.7.10 is no longer supported. Try the latest jenkins version, someone PRed a fix for this that never got released.

**Comment by DeadSix27** [comment]
Alright I will check it out, thanks and ye I figured its not supported anymore, but a lot of people still play 1.7.10 simply because lots of big mods simply won't get updated... Mainly AE2 :P but that seems to be being worked on (and some other mods) once those get updated .. maybe ...

ANYWAY "Fix hammers can't be automatically inserted (commit: 40ba7719074d121d2ee0236bfc8617a90f50b6e7) — guhenry3 / detail"
@Jenkins thats all I needed, if the dev version works fine.. I'm happy :) Thanks!
