### ISSUE TITLE
Heavy auto sieve shows RF usage and progress animation in GUI but input slot is empty

### ISSUE THREAD

**Issue by MatthiasMann** [blay09/ExCompressum#136]
But looking at TOP no RF is actually consumed. This animation is repeated every time the UI is opened and runs until the RF storage is empty - no items are produced by this.

I haven't tested other auto machines.
Version is ExCompressum 1.10.2-2.0.40

**Comment by MatthiasMann** [comment]
PS: When items are in the input slot the machines works as expected - eg progress animation stops when RF storage is empty and continues correctly when RF is supplied.

**Comment by blay09** [comment]
I can't reproduce this.

The block moves one input item into an internal buffer as it processes it, maybe that's what you were seeing?

**Comment by RealGrep** [comment]
Yeah, it works like the EIO Alloy Smelter and others, where the block currently being processed is not in the input slot. Bet that's what's being seen, because all other blocks are showing up fine in the input slot for me.
