### ISSUE TITLE
(1.10.2) Crash while breaking Compressed blocks with Compressed Diamond Hammer

### ISSUE THREAD

**Issue by Farronox** [blay09/ExCompressum#137]
Will report to Tema too as I'm not sure if it's a ExC or ExtraUtils issue. 

http://pastebin.com/XXVnRYAw

**Comment by blay09** [comment]
This was fixed (#133), forgot to release it on Curse.

http://jenkins.blay09.net/job/Ex%20Compressum%201.10.2/lastSuccessfulBuild/
