### ISSUE TITLE
Compr. Crook broken on Adscensio?

### ISSUE THREAD

**Issue by blay09** [blay09/ExCompressum#138]

**Comment by jdratlif** [comment]
This sounds like what I told Darkosto on his twitch stream earlier. If not, sorry I hijacked your issue; let me know and I'll open a new one.

Breaking infested leaves with a compressed crook results in no drops (string or anything else). It seems to work fine with normal leaves (getting saplings, apples, and silkworms). I can get string from infested leaves being broken with wood or bone crook from adscensio, but not from compressed crook from ex compressum.

MC 1.10.2
Forge 2099
Ex Compressum 2.0.44 (from Jenkins) -- I also tried 2.0.40 just in case, but no change.
Ex Nihilo Adscensio 0.0.30

Thanks.
