### ISSUE TITLE
[1.7.10] Smashing modifier not firing block break

### ISSUE THREAD

**Issue by Funwayguy** [blay09/ExCompressum#141]
I've had a number of reports about Ore Excavation not functioning correctly in Sky Factory 2.5 when using the smashing modifier. After a bit of digging I ran across these lines of code and came to the conclusion that your mod may not be correctly firing Block Break events on behalf of the player (or prematurely deleting the block before the event can properly fire).

https://github.com/blay09/ExCompressum/blob/master/src/main/java/net/blay09/mods/excompressum/compat/tconstruct/ActiveSmashingMod.java#L50

Would it possible to get this resolved in time for Sky Factory update v2.5.7?

Funwayguy/OreExcavation#6

**Comment by blay09** [comment]
Let me know if it works and I'll put it up on Curse.

http://jenkins.blay09.net/job/Ex%20Compressum%201.7.10/148/

**Comment by Funwayguy** [comment]
Seems the modifier doesn't work at all any more even without Ore Excavation installed
