### ISSUE TITLE
Load order cycle with new Ex Nihilo Omnia due to before:jei dependency

### ISSUE THREAD

**Issue by RealGrep** [blay09/ExCompressum#144]
Support for Forestry has been added with the most recent Ex Nihilo Omnia (1.2.1). It therefore requires to be loaded after Forestry. But Forestry has the dependency `after:jei` whereas this mod requires to be loaded after Ex Nihilo Omnia, and before jei. That cannot be satisfied.

I notice it was introduced with this commit: https://github.com/blay09/ExCompressum/commit/49fdd21adc5acd226def0d80fab9b5106bb461cf

I've removed the `before:jei` and it seems to be working just fine. I can see the heavy sieve recipes in JEI from compressed blocks. Is this strictly necessary? And if there are issues I just haven't found, can it be done some other way? Because this is a nasty little impasse, right now.

This is using Ex Compressum 2.0.54 for MC 1.10.2.

While I'm at it, should it not be loaded after Botania as well?

May as well ping @Jozufozu so he knows this is going on.

Thanks!

P.S. Should the 'Issues' on CurseForge not be linked to this Github issue tracker instead of Curse's? I logged something there earlier, so you might want to check in on it. XD

**Comment by blay09** [comment]
https://github.com/Jozufozu/ExNihiloOmnia/issues/102

It's necessary at the moment when using Ex Nihilo Adscensio, I've reached out to the dev to register their stuff earlier so I can register my stuff earlier, but will probably just go ahead and release a non-before:jei version tomorrow, since it's only the JEI integration for Adscensio that will break.

**Comment by RealGrep** [comment]
Ok, thanks a lot :)

**Comment by blay09** [comment]
Uploaded a build that solves the issue (and breaks Adscensio JEI support for the time being).
