### ISSUE TITLE
Unable to pipe diamond hammers into the auto hammer

### ISSUE THREAD

**Issue by canassa** [blay09/ExCompressum#148]
Hello,

I was trying to automate to installation of upgrades into the auto hammer, but I noticed that if I try to pipe a diamond hammer into auto hammer it wont accept it. Manually putting the hammer works, so I am sure that I am using the correct hammer for the job 😉 

I haven't test the books on the auto sieve, but I suspect that they suffer from the same issue.

I am using the latest version of the Infinity Evolved Skyblock pack (Minecraft 1.7)

**Comment by blay09** [comment]
1.7.10 is no longer supported. Try the latest jenkins version for 1.7.10, someone PRed a fix for this that never got released.
