### ISSUE TITLE
[Request] Ex Compressum MineTweaker/ModTweaker Support (Heavy Sieves, etc.)

### ISSUE THREAD

**Issue by Wealthyturtle** [blay09/ExCompressum#151]
Sorry if this Minetweaker/ModTweaker Support Already Exists, but According to the Minetweaker & Modtweaker Wikis, as well as Your Website (I Didn't Check All of it), this Support Doesn't Exist?

As a Modpack Maker that Heavily Relies on Tweaking Recipes, I think that would Work with [Ex Nihilo's Current Modtweaker Support](http://minetweaker3.powerofbytes.com/wiki/ModTweaker:Ex_Nihilo_Support).

Thanks!

**Comment by blay09** [comment]
Ex Compressum already provides options to change drops without the use of MineTweaker, see config/excompressum/HeavySieve.json for example.

**Comment by Wealthyturtle** [comment]
Thanks :)
