### ISSUE TITLE
Autocompressor

### ISSUE THREAD

**Issue by Synize** [blay09/ExCompressum#152]
Seems when you sieve compressed dust and pipe into the autocompressor it doesn't always stack the dusts. Which leads to the input slots sometimes getting full of like items

**Comment by blay09** [comment]
What version?

**Comment by Synize** [comment]
ExCompressum_1.10.2-2.0.56

Tested this on the vaygrim chance 4 pack.

**Comment by blay09** [comment]
Actually the input stacking logic comes from whatever pipe you're using to input into the auto compressor. The Auto Compressor doesn't make any choices as to where incoming items end up other than exposing a grid of slots.
