### ISSUE TITLE
[1.10.2] Compressed hammer 

### ISSUE THREAD

**Issue by YOYOK9** [blay09/ExCompressum#153]
When looking at JEI it says that if you break a double compressed block from extrautils 2 you should get 9 blocks of the next tier... However when you break a compressed block you receive 36 blocks of the next tier.   Tested with all compressed hammers

**Comment by blay09** [comment]
Double compressed blocks aren't a default thing, so whatever pack you're using must have configured it wrong.

**Comment by YOYOK9** [comment]
Sorry ment single compressed. But the dup is the same. Also configs are the default for both mods.

**Comment by blay09** [comment]
Compressed Hammers can act as normal hammers, if there's a bug in Omnia it needs to be fixed over there. Still sounds like a configuration issue to me since neither supports double compressed blocks by themselves. Everything is working fine in my dev environment.

**Comment by blay09** [comment]
This is probably #165. You need to specify if you use SpongeForge, it makes a difference.
