### ISSUE TITLE
Lag Mayham when Interacting with EnderIO Conduits / Machines

### ISSUE THREAD

**Issue by desagas** [blay09/ExCompressum#161]
I have not been able to find information anywhere on this issue.

I am playing on SkyFactory3.04, with inventory tweaks installed client side only, and when I try to pull out of or push into the Auto Hammer / Sieve with any enderio machine or conduit, I get immediate lag. This is only tested with items where there is an issue. Using conduits for pwoer does not cause lag at all.

**Comment by blay09** [comment]
Using EnderIO 3.1.161, EnderCore 0.4.1.65 and Ex Compressum 2.0.68, I can't reproduce this. I inserted into and extracted from an Auto Sieve with EnderIO Item Conduits without any FPS or TPS drops, and there's nothing suspicious in the profiler logs.

If you can reproduce it, and you're running the latest versions of all mods involved, try running `/debug start` when the lag issues start appearing, wait a few seconds, then run `/debug stop` and post the resulting profiler logs (`.minecraft/debug/profile-results-....txt`) on pastebin. That might help figuring out what's causing the problem.

**Comment by desagas** [comment]
I do not know what the versions of the mods were. But, I did say the pack version, if those are the same versions of the mods in the pack, great, then it was just my computer and Hypnos and xbcrafteds, and many other computers out there. Are they the same versions of the mods?

But, that pack, at that time, on many computers was cause some sort of issue. I do not know if it was TPS or Frame or what.

I did have about 6 hammerers and 3 sieves.

That being said, if it does not work on newer versions, then it was fixed, which is great. I am also done playing the pack, so I won't be checking or testing it anytime soon.

Thanks for looking into it. :)

Denver Leman

On Feb 3, 2017, at 4:48 AM, BlayTheNinth <notifications@github.com<mailto:notifications@github.com>> wrote:


Using EnderIO 3.1.161, EnderCore 0.4.1.65 and Ex Compressum 2.0.68, I can't reproduce this. I inserted into and extracted from an Auto Sieve with EnderIO Item Conduits without any FPS or TPS drops, and there's nothing suspicious in the profiler logs.

If you can reproduce it, and you're running the latest versions of all mods involved, try running /debug start when the lag issues start appearing, wait a few seconds, then run /debug stop and post the resulting profiler logs (.minecraft/debug/profile-results-....txt) on pastebin. That might help figuring out what's causing the problem.
