### ISSUE TITLE
Compressor in line with Auto Hammer/Sieve system does not pass-through non-compressible items

### ISSUE THREAD

**Issue by notacompletemoron** [blay09/ExCompressum#167]
Updated from Sky Factory 3.0.1 to 3.0.4 release (2016-01-06).

Compressor DOES NOT pass through items that cannot be compressed. Gunpowder, ancient seeds, yellorium dust, crushed black quartz, etc.

Using version ExCompressum_1.10.2-2.0.54 in SF3 3.0.1 worked.

Using version ExCompressum_1.10.2-2.0.68 in SF3 3.0.4 is broken.

My setup is 1x T4 cobble gen into 9 auto hammers (layered setup), 3 go into sieves (for gravel), 6 go into another set of hammers. From there 3 go into sieves (for sand), and the last 3 go into another set of hammers, which go into the last set of sieves (dust). All sieves are output into 3 compressors in series, which the last outputs into a chest.

**Comment by blay09** [comment]
You were probably experiencing a bug that has been fixed, which was allowing items (all, even compressible ones) input using pipes to end up in output slots if the input was full. That was never intended and there is no "pass-through" mechanic for non-compressible items.

See #146 for original issue report of the bug that was fixed.
