### ISSUE TITLE
Compressed mobs breaking Ender IO Powered spawner

### ISSUE THREAD

**Issue by Hazmatik** [blay09/ExCompressum#174]
It seems after killing a compressed mob and then all the mobs that spawn after it they are still being counted as being there by vanilla code causing the Ender IO powered spawner to think there are too many mobs in an area.

https://www.reddit.com/r/feedthebeast/comments/5lx9n9/sky_factory_3_powered_spawner_bug/

http://i.imgur.com/tZaI4iB.png

**Comment by EPIICTHUNDERCAT** [comment]
Is that what it is! oh woww!

**Comment by blay09** [comment]
I *think* this may be fixed by v2.0.76.
