### ISSUE TITLE
Evolved Orechid

### ISSUE THREAD

**Issue by aquilon74** [blay09/ExCompressum#176]
I've seen in modpacks with garden of glass and ExCompressum that orechid and evolved orechid have the same recipe. Is there a way to craft the evolved one ?

**Comment by blay09** [comment]
There's no need for the evolved one if you're playing Garden of Glass, they're literally the same. It was added to bring the Garden of Glass orechid into non-Garden of Glass skyblocks. So if you're already playing on Garden of Glass mode, you don't need it.
