### ISSUE TITLE
Compressed Mobs Problem!

### ISSUE THREAD

**Issue by YOYOK9** [blay09/ExCompressum#178]
I Updated to the latest version of ExCompressum and I've noticed that all my mobs spawning are compressed. There are no "uncompressed" mobs spawning at all. I checked the config and the spawn chance says: 

.# The chance for mobs to spawn as Compressed Mobs. Set to 0 to disable. [range: 0.0 ~ 1.0, default: 0.01]
    S:"Spawn Chance"=0.01

But they are spawning it seems at 100%. 

ExCompressum_1.10.2-2.0.77.jar
Worked fine in previous update.

**Comment by blay09** [comment]
Are you sure you're running .77?

**Comment by YOYOK9** [comment]
Huh apparently not... Feel kinda stupid now. Let me try .77

**Comment by YOYOK9** [comment]
My bad guess I updated my pack just before you posed .77. It all works now. Sorry about that
