### ISSUE TITLE
Extra Utilities Compressed blocks not working

### ISSUE THREAD

**Issue by zedner** [blay09/ExCompressum#179]
Tried stone compressed hammer on compressed sand gravel... from extra utilities and it doesn't work when I mine it with compressed hammer it drops the same block, ore smasher bugged too, it doesn't smash ores into crushed versions.

**Comment by zedner** [comment]
Btw im using latest ex compressum (1.10.2-2.0.77) and latest extra utilities for 1.10.2 (1.2.0)

**Comment by sdaddy** [comment]
Piggybacking off this issue. Since this update I can no longer craft any of the compressed hammers or the crook and the recipes no longer show in JEI. I used Minetweaker to create a recipe and the hammer failed to work like the above comment mentions.

**Comment by stefan-schweiger** [comment]
@blay09 while the hammer/autohammer now works the heavy sieve/auto heavy sieve are still broken.
