### ISSUE TITLE
Oak Crucible - Constantly takes water

### ISSUE THREAD

**Issue by MercerK** [blay09/ExCompressum#181]
I'm trying to automate the filling of the oak crucible with water, however, when it reaches 1000, it continues to suck water. This is an issue when playing with mod packs with infinite water is disabled, such as Forever Stranded. I tested with pipes from Extra Utilities and Ender IO.

**Comment by blay09** [comment]
The Oak Crucible was done like that to allow buckets being emptied into a partial filled crucible. It's kind of a workaround for the Forge system not allowing that easily at the moment.

Do you have barrels available? You could fill those to get clay instead. I'll probably see if I can get some changes into Forge to have a proper fix for this.

**Comment by OrangeCorduroy** [comment]
In relation to this, if you are pulling water out of an oak crucible, you can add items into the crucible as soon as the solid volume is below 1000units which causes a loss of items.  I was also playing forever stranded, have extra utilities pulling out water and putting in leaves and this was happening.  This also can be seen when using Ender IO pipes and putting items into the oak crucible by hand.

So

**Comment by Zeure** [comment]
Just wanted to put in that this second issue of being able to add items to an oak crucible immediately after it takes the first 8 mb out is still present; but that it wasn't in a previous version as I had a set up that was working fine before but in the current version is not.  Also playing Forever Stranded.

**Comment by blay09** [comment]
This will be fixed in the upcoming 1.12 version.

**Comment by tifkat** [comment]
Which is fixed? The constantly taking water or taking items when <1000mB present?
