### ISSUE TITLE
Suggestion: extended information for null reward errors?

### ISSUE THREAD

**Issue by DeadSix27** [blay09/ExCompressum#184]
`[net.blay09.mods.excompressum.ExCompressum/]: Tried to roll sieve rewards from a null reward entry: exnihiloadscensio:blockDust (base chance: 0.03, mesh level: 1)`

See: https://github.com/blay09/ExCompressum/blob/f22e3aae2493c0396021e19a62b0665a68b3407a/src/main/java/net/blay09/mods/excompressum/compat/exnihiloadscensio/ExNihiloAdscensioAddon.java#L191

Within `for (Siftable siftable : siftables) {`

https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/469eb9dbbd73ee0057894a8eca66296e79849b65/src/main/java/exnihiloadscensio/registries/types/Siftable.java#L11

Is it possible to just use `siftable.drop.toString()` in the error message to make it easier to idenfiy the wrong sieve entry?

## EDIT:
Guess its not possible unless ExAdscendio adds a new property to https://github.com/MikeLydeamore/ExNihiloAdscensio/blob/469eb9dbbd73ee0057894a8eca66296e79849b65/src/main/java/exnihiloadscensio/util/ItemInfo.java

that holds the original string from the class creation `public ItemInfo(String string)`
but idk..

**Comment by blay09** [comment]
This is something that should be fixed on Adscensio's site in the first place (=> refusing to load the entry rather than just loading it as null, and adding its own log message). My check is just in place to prevent Ex Compressum from crashing if it comes along something like this.
