### ISSUE TITLE
Workaround for "overflowing" items on (heavy)sieve? 

### ISSUE THREAD

**Issue by DeadSix27** [blay09/ExCompressum#185]
With Fortune10 on the meshes (kinda cheaty ik, but if you have a mod that can do that...) 
sieves will overflow and drop the items on the ground, any possible way to work-around that? e.g make the sieve auto push all the items into a adjacent (diamond)chest or so.

**Comment by blay09** [comment]
Rather than adding a new feature for weird edge cases like this, Fortune should probably be fixed to not fill your entire inventory on higher fortune levels. #186
