### ISSUE TITLE
ExCompressum and EnderIO server crash

### ISSUE THREAD

**Issue by joelaw9** [blay09/ExCompressum#188]
Minecraft 1.10.2
Sky Factory 3: 3.0.7
ExCompressum: 2.0.87
EnderIO: 3.1.171

On a multiplayer server of Sky Factory 3 when adding an ExCompressum auto heavy sieve or auto compressed hammer to an Ender IO piping network, the server crashes with this error:
[crash-2017-03-08_14.44.56-server.txt](https://github.com/blay09/ExCompressum/files/829070/crash-2017-03-08_14.44.56-server.txt)

Specifically, it's when I enable inserting from the primary channel from the Ender IO interface.

The other things on the same network are other heavy sieves and hammerers, Crafters (RFTools), SAG Mills (Ender IO), Furnaces (Extra Utilities 2), Crusher (Extra Utilities 2), Cobblestone Generator (Tiny Progressions), Small Storage Crates (Actually Additions), Loot Bag Opener and Recycler (Loot Bags), and Drawer Controllers (Storage Drawers).

**Comment by blay09** [comment]
Do not attempt to insert pistons into Ex Compressum machines when you have Foamfix installed.
