### ISSUE TITLE
Nether Gravel Ardite/Cobalt

### ISSUE THREAD

**Issue by ecoay** [blay09/ExCompressum#190]
Didn't ex compressum used to be compatible? If not I think it would save everyone a lot of headache making custom configs since I have never played a pack without ardite/cobalt.

**Comment by blay09** [comment]
What?

**Comment by bookerthegeek** [comment]
@ecoay qyick question is what mod adds that as Tinkers Construct no longer has gravel versions of their ore in 1.10

**Comment by ecoay** [comment]
Ex Nihilo Omnia has cobalt and ardite from sieving nether gravel. If you want to do it all by hand. It is not a product of auto-sieving in ex compressum.

**Comment by blay09** [comment]
Auto-sieving pulls from the same registry as normal Omnia sieves.
