### ISSUE TITLE
AutoSieve Skins Feature request?

### ISSUE THREAD

**Issue by tyler489** [blay09/ExCompressum#191]
Is there a way to make only certain skins show up in the autosieve/autohammer?  Im guessing thos are patreon skins. If possible would like to be able to list usernames in a cfg file to use

**Comment by blay09** [comment]
Yes, they're Patreon skins. Not making them a configurable list was a choice, it *is* a Patreon reward after all. You can disable the skin loading in the config and lock it to just Steve though.
