### ISSUE TITLE
reloading excompressum does not update JEI/NEI sieve rewards

### ISSUE THREAD

**Issue by lolorz13** [blay09/ExCompressum#196]
editing HeavySieve.json with new entries then doing "/excompressum reload" does not cause sieve rewards in JEI/NEI to update however the effects do update and work ingame.  New entries also do not appear if added in.
**Edit**
forgot to mention that reloading works, but can take a long time when working with large packs hence why this is an issue

**Comment by tjdagamer** [comment]
i have a problem where i cant get any rewards from auto sieves. sieves themselves just repeat the block. what happens is the block gets to the bottom and just teleports to the sieve top and repeats getting sieved for infinity with no reward. 

btw, should i make a new thread for this issue?

**Comment by blay09** [comment]
Runtime reloading is no longer supported by JEI, I don't think there's anything I can do to make it update.
