### ISSUE TITLE
excompressum iron mesh level custom recipe issue

### ISSUE THREAD

**Issue by lolorz13** [blay09/ExCompressum#197]
ExCompressum/src/main/java/net/blay09/mods/excompressum/registry/sievemesh/SieveMeshRegistry.java
line 20: ironMesh.setMeshLevel(3);
Should excompressum's iron mesh be set to a different level? if set to lvl 3, it seems to be impossible to create custom sieve recipes for it because ex nihilo adscensio's iron mesh is also level 3 and new recipes get added to that mesh instead.  If you believe this mesh should not be changed, is there a continued need for it?

**Comment by blay09** [comment]
The iron mesh is uncraftable with Adscensio installed. They're supposed to be equivalent.
