### ISSUE TITLE
Auto Sieve don´t accept Energy

### ISSUE THREAD

**Issue by Lauro3101** [blay09/ExCompressum#201]
Hey, i´m currently playing Sky Factory 3 and wonder why my Auto Sieve doesn´t accept RF (from Ender IO) it says "0 FE" but i don´t really know what "FE" is...

**Comment by kaluzki** [comment]
can confirm it. i tried out two last versions (ExCompressum_1.10.2-2.0.87 and ExCompressum_1.10.2-2.0.97.jar) in combination with **coal generator** from **actually additions**.

**Comment by kaluzki** [comment]
2.0.68 seems to be the last version where your machines accept energy from **actually additions**

i've also tested briefly your mod with **sky factory 3.0.12** 
energy sources from **Solar Flux Reborn** and **actually additions** are not accepted by your machines,
but **simply generators** and **ender io** seem to work properly

**Comment by blay09** [comment]
see #177 

I can't be bothered to re-add RF to the 1.10.2 version but it'll probably be supported again if Ex Compressum is ported to future versions. Back then RF was considered dead and Forge got a common energy interface that mods can support and people seemed to adapt just fine, so I'm not sure why there's suddenly issues appearing now. Maybe you're running outdated versions, or other mods started reverting their changes.

**Comment by blay09** [comment]
The upcoming 1.12 version adds RF support again.
