### ISSUE TITLE
[1.7.10 version] A very serious bug.

### ISSUE THREAD

**Issue by RainEffect** [blay09/ExCompressum#204]
When the player's backpack is filled, through use **"shift + left"** to quickly pick up the items, will lead to items become 64.
(PS: I'm sorry my English is not very good)

![default](https://user-images.githubusercontent.com/14258727/28743122-990091a8-7474-11e7-83cd-3b8e61c961ed.gif)

**Comment by blay09** [comment]
Did this happen on the latest version for 1.7.10? I tried but it's not happening for me.
