### ISSUE TITLE
[Question] Any Possibility of an update to 1.12?

### ISSUE THREAD

**Issue by Tylerun** [blay09/ExCompressum#206]

**Comment by blay09** [comment]
I would, but I don't think there's any Ex Nihilo out for later versions yet.

**Comment by Tylerun** [comment]
https://github.com/BloodWorkXGaming/ExNihiloCreatio. He took over for ExNihilo Adcensio

**Comment by blay09** [comment]
I'd like to wait for a proper release before committing my time to a port, to make sure it isn't wasted.
