### ISSUE TITLE
Option to drop compressed blocks instead of 9 uncompressed blocks

### ISSUE THREAD

**Issue by gavinrobertkemp** [blay09/ExCompressum#207]
is there the possibility to have the option of double compressed hammer upgrade drop compressed blocks or even matter balls type entity from equivalent exchange? I was playing around with automating a tinkers hammer with this upgrade but it brutal on the tick rate when you're breaking 21 blocks of compressed cobble stone at the same time. I expect a similar issue would come from the compressed sieves. I know auto hammer and auto sieves exist but I find this version more fun easier to scale and reward smart design.

**Comment by blay09** [comment]
The upcoming 1.12 version adds a Compressing modifier for Tinker's tools, which turns drops into their compressed form.
