### ISSUE TITLE
Do not let in

### ISSUE THREAD

**Issue by Awsmit** [blay09/ExCompressum#208]
When opening the minecraft (vr. 1.7.10) the console jumps me an error of "UE" is the only mod that I miss that error ... help me please 
![image](https://user-images.githubusercontent.com/30969804/29246347-7640af9c-7fbc-11e7-8c14-7065fb3b0e1b.png)

I have tried the version excompressum-mc1.7.10-1.1.143.jar and excompressum-mc1.7.10-1.1.149.jar

**Comment by blay09** [comment]
Post the actual log, not just a screenshot of the part that said "some error happened".

**Comment by Awsmit** [comment]
Can you explain what the actual record is ... please do not understand. Thanks for answering

**Comment by blay09** [comment]
Click `Open Report File`, paste the content into https://pastebin.com/ and then post the link here.

**Comment by Awsmit** [comment]
Wow, I did not know there was that button. Look here is the link, I hope and you can help me <3
https://pastebin.com/BtfcjvbB

**Comment by blay09** [comment]
You need to update Ex Nihilo to the latest version.

**Comment by Awsmit** [comment]
Puto master, I owe you the dear life olimpo god!
