### ISSUE TITLE
1.10.2 Problem

### ISSUE THREAD

**Issue by SalmonTheBoss** [blay09/ExCompressum#210]
I installed the mod and I put it in my mods folder and launched my minecraft but it kept crashing, it said this
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Ex Compressum (excompressum)
Please help, Thanks

**Comment by blay09** [comment]
It said more than that. There is not a single bit of useful information in the excerpt you posted, so I'm not sure how you expect me to come up with a solution.

Anyways, update your Ex Nihilo to the latest version, it's probably that.

**Comment by SalmonTheBoss** [comment]
But that mod is in 1.7.10?

**Comment by blay09** [comment]
https://vazkii.us/br101/
