### ISSUE TITLE
 ExCompressum_1.12.1-3.0.6.jar

### ISSUE THREAD

**Issue by xKnightGamingx** [blay09/ExCompressum#213]
That version is not showing up on the twitch launcher since you released it 1 day ago

**Comment by YOYOK9** [comment]
I am Having the same issue. Can't see it on the launcher for 1.12.1 or 1.12

**Comment by xKnightGamingx** [comment]
Thing is I have been waiting over two days for answer on why and still no message or fix

**Comment by blay09** [comment]
Latest shows up for me now. I have no control over what files show up and when, if it's still not working for you, take it to Twitch support.
