### ISSUE TITLE
[1.12.1] [TCon API] Trying to register a modifier

### ISSUE THREAD

**Issue by HendrikJ79** [blay09/ExCompressum#214]
[OpenEye Log](https://openeye.openmods.info/crashes/5a97ca1ceb7cab15b87931090f83eea4)
[Crash Log](https://gist.github.com/HendrikJ79/14eed57d656dfa470e5574aa0b84d710)

**Comment by blay09** [comment]
This is already fixed, it just seems like Curse is having issues getting the file on their client.

https://minecraft.curseforge.com/projects/ex-compressum/files/2478266

**Comment by blay09** [comment]
Latest version should be available on the client now.
