### ISSUE TITLE
1.12 Auto Heavy Sieve Enchantments?

### ISSUE THREAD

**Issue by scottwilson0308** [blay09/ExCompressum#215]
Hey there,

First off, great mod! Can't live without it anymore in Skyblock. Just wondering if there's a way to pass on Sieve Enchantments to the Auto Heavy Sieve.. I've enchanted a diamond mesh with Fortune III, and it definitely works on the Heavy Sieve, but not the Auto Heavy Sieve.. am I doing something wrong, or is this intentional?

**Comment by scottwilson0308** [comment]
(Sieve Fortune III, of course)

**Comment by blay09** [comment]
What Ex Nihilo are you using? I can't even get my diamond meshes enchanted at all (Ex Nihilo Creatio).

**Comment by scottwilson0308** [comment]
Ex Nihilo Creatio as well. All I did was put a diamond stiffened mesh into a vanilla anvil with a Sieve Fortune III book and it worked without a hitch. Placing that mesh into a Heavy Sieve drastically improved my output, but into an Auto Heavy Sieve it made no difference. Ran the math and the Heavy Sieve is distinctly improved.

**Comment by scottwilson0308** [comment]
I've actually managed once to enchant the Auto Heavy Sieve itself in the past, but didn't notice anything in particular. Will try it again and double-check if that makes a difference.

**Comment by blay09** [comment]
What probably happend was that you used `Fortune III` with the Heavy Sieve, and `Sieve Fortune III` with the Auto Heavy Sieve. Creatio only recently added back the enchantments and Ex Compressum did not support them yet.
