### ISSUE TITLE
Server crash on death of Compressed Mobs with TCon weapon

### ISSUE THREAD

**Issue by Gunner76th** [blay09/ExCompressum#216]
I had a player that built the Shuriken weapon from Tinker's Construct, and any time he uses it to kill a compressed mob the server crashes. The modpack in use is The World of Arrakis https://mods.curse.com/modpacks/minecraft/278667-the-world-of-arrakis

The crash that is generated is https://pastebin.com/iXEx4FgZ

The pack version in use is Beta 0.3 (Current)

**Comment by Hasselpoof** [comment]
here is the stats and info on the weapon that was used and was crashing the server when killing compressed mobs.

i have been using a normal sword from tinkers to kill with to, but never crashed then

![tool stats 2](https://user-images.githubusercontent.com/8875740/31594892-32a1d06e-b238-11e7-8ff1-a2927410be30.PNG)
![tool stats 1](https://user-images.githubusercontent.com/8875740/31594893-32b9c714-b238-11e7-95ba-713796812573.png)
