### ISSUE TITLE
Heavy Sieve Recipe makes wooden crucible?

### ISSUE THREAD

**Issue by blay09** [blay09/ExCompressum#217]
Apparently Creatio hijacked a recipe I was using for nearly two years, so I'm thrilled to fix this (but not really)

**Comment by ThEpicFail** [comment]
Just get (no more crafting recipes (In one word)) , it's a mod where you can change the recipe outcome if multiple mods have the same recipe but different outcomes.

**Comment by masternetra** [comment]
@ThEpicFail - You'll have to link to it. I can't find ANY mod called "no more crafting recipes" not on curse or google. Apparently you got the name wrong.

**Comment by bochen415** [comment]
@masternetra https://minecraft.curseforge.com/projects/stimmedcow-nomorerecipeconflict
