### ISSUE TITLE
[Question] costume hammer registry

### ISSUE THREAD

**Issue by Kasparsunekaer** [blay09/ExCompressum#221]
So in Ex Nihilo Creatio my hammer registry is set this way:
Stone -> Cobblestone -> Gravel -> Dirt -> Sand -> Dust

Is there any way i can set Compressed hammers to works this way?
I dont see any Compressed Dirt in Ex Compressum but Extra Utilities 2 has compressed dirt, and i see that EX2´s compressed coblestone, gravel, sand works

forge-1.12.2-14.23.1.2554
ExCompressum_1.12.2-3.0.11

**Comment by blay09** [comment]
CompressedHammer.json in config folder lets you define custom entries.

**Comment by Kasparsunekaer** [comment]
Okay thanks
now i have the problem with then i place a compressed dirt block and use the compressed hammer on it, it takes a very long to hammer, and then the block breaks and nothing drops
compressed gravel to dirt works fine
Here´s my current config: https://pastebin.com/99YBNs90
am i doing something wrong regrading Compressed dirt to sand?

**Comment by Kasparsunekaer** [comment]
nvm found a missing }
