### ISSUE TITLE
Heavy Sieve 

### ISSUE THREAD

**Issue by GWSheridan** [blay09/ExCompressum#222]
Mc version: 1.12.2
Forge version: 14.23.1.2561
Mod version: 3.0.11
Issue: When sieving gravel in the heavy sieve it takes one click to get items even if configs say takes 24 or 6 clicks

**Comment by blay09** [comment]
The option you're looking at is `The maximum amount of clicks per second on a heavy sieve. Clicks above this will be ignored.`. That's not the speed at which it sieves. The speed is fixed, and the reason it's only taking one click is because you're probably in Creative Mode.
