### ISSUE TITLE
Compressed mobs

### ISSUE THREAD

**Issue by flareflamer** [blay09/ExCompressum#223]
Mc version: 1.12.2
Forge version: 14.23.0.2515
Mod version: 3.0.11
Issue: Compressed mobs do not break into the intended amount of the singular mob instead it drops a "name tag" indicating the specific compressed mob name.

**Comment by blay09** [comment]
What other mods are installed?

**Comment by flareflamer** [comment]
Im using this version of "allthemods 3 v.4.3" modpack. I just recently pick up your mod. Im going to test it again with the newest version of forge and modpack to see the problem persist again.

**Comment by blay09** [comment]
Some mod is making mobs drop nametags when they're named. I don't know which it is. And it looks like it's also cancelling the event Ex Compressum requires in order to split the mobs. I might be able to work around it by having my handler fired first, but it's still a pretty broken assumption to do `named mob => drop nametag` in the modded world.

**Comment by flareflamer** [comment]
I apologise for the late reply. It works on 1.10.2 for the most mods. Only normal attacks uncompress the compressed mobs so far that i discovered. From what i tested so far, mob grinding blocks do not uncompress compressed mobs and only drop nametags. Im not sure is it your work to code or the mod packers.

Identified mods so far:
Mob_grinding_utils
Extra utilities 2
draconic Evo ( mob grinder)
Cyclic

**Comment by blay09** [comment]
Mob grinders are supposed to not uncompress mobs as it has the potential of breaking automated mob farms. It's only supposed to work for attacks by players.

The nametags - that's still some other mod dropping them, but as long as it's working fine for player attacks, there's no problem as far as Ex Compressum is concerned.
