### ISSUE TITLE
[Request] Option to turn off Compressed mob death messages

### ISSUE THREAD

**Issue by NillerMedDild** [blay09/ExCompressum#226]
Hey! 

I'm playing on a server that has a few mob farms, and a few times each minute the message "Compressed mob was killed by..." is broadcasted. It's getting a little annoying. 
Would you mind making a config to turn broadcasting on/off? :)

Minecraft 1.12.2

**Comment by MrNinja93** [comment]
This is probably the fault of the Thermal suite of mods, In configs click on the cofh folder then core folder and then common.cfg and change 
`B:EnableGenericDeathMessage=true` to false 

Server side will need to change it to stop it broadcasting on a server.

**Comment by NillerMedDild** [comment]
I see, thank you :)
