### ISSUE TITLE
[1.12.2] Auto Compressor Dupe Ores

### ISSUE THREAD

**Issue by GWSheridan** [blay09/ExCompressum#231]
When placing ore pieces from ex nihilo creatio in the auto compressor let it compress all items to ore chunks. Then break the compressor it will give back all the ore pieces an the ore chunks it created

Versions 
MC: 1.12.2
Forge: 14.23.1.2600
Ex Nihilo: Creatio: 1.12-0.1.7
Ex Compressum: 1.12.2-3.0.13

**Comment by kwpugh** [comment]
if the auto compressor has been running in an automated fashion for a while, it gives thousands.   I got 8000 sand and 6000 gravel, there was only a few blocks of each shown in the gui

**Comment by GWSheridan** [comment]
Thanks blay for the fix
