### ISSUE TITLE
Cow bait in a compact machine crashes client

### ISSUE THREAD

**Issue by lpacphantom** [blay09/ExCompressum#233]
I'm playing the Forever Stranded Lost Souls modpack and needed to get a cow for some quests. I tried the bait, but since it's the nether, you can't place water, so it can't be done in the main dimension of the modpack. So I tried it in a compact machine since it's a different dimension and I can place water there. Then my client crashed. 

Here's the crash log.
[crash-2018-02-15_19.17.06-client.txt](https://github.com/blay09/ExCompressum/files/1729835/crash-2018-02-15_19.17.06-client.txt)

**Comment by blay09** [comment]
Try the latest Compact Machines version, from the changelog it sounds like they fixed this.
