### ISSUE TITLE
HeavySieve Auto-generate from Adscensio crash

### ISSUE THREAD

**Issue by DiggyDigger456** [blay09/ExCompressum#235]
[crash-2018-02-25_21.45.41-server.txt](https://github.com/blay09/ExCompressum/files/1757204/crash-2018-02-25_21.45.41-server.txt)

I added an ore to OreRegistry and SieveRegistry in ExNihiloAdscensio and the registry auto-gen for ExCompressum didn't register the new ores

**Comment by blay09** [comment]
Most likely the Adscensio configuration is incorrect - check the log for errors during Adscensio loading. An item name is probably misspelt. Sadly, Adscensio did not properly protect against these cases back then.
