### ISSUE TITLE
Placing chicken baits crashed the game

### ISSUE THREAD

**Issue by Darkmega18** [blay09/ExCompressum#240]
[crash-2018-05-28_18.00.13-client.txt](https://github.com/blay09/ExCompressum/files/2044200/crash-2018-05-28_18.00.13-client.txt)

Just sending this one in. I tried to place some chicken baits and my game went nuclear. There were a fair few cows around, is is something erroring with the checking of the "too many animals here" part?  The cow baits had worked perfectly fine earlier when I didn't have as many animals, but over time I bred up the cows I did have so they were kind of everywhere.

upon going back in and pulling the cows over the other side of the base then doing the baits again, no crash for any of them.

**Comment by blay09** [comment]
Does this happen consistently? This crash is technically impossible, and while I've seen it a few times, I've never been able to reproduce it.

**Comment by Darkmega18** [comment]
it hasn't happened again since. so I'm not sure what triggered it. Cause I've been spawning animals a decent amount and letting them just free range on my platform until I gotta spawn more where I then bring them to one side and do the baits quickly.

**Comment by blay09** [comment]
It seems to be pretty rare, and while I could try and fix it through a simple check, it would only hide the real problem further and result in broken environment checks. 

Unless I've gone fully insane there is no way for this issue to occur without 1) there being some weird issue in the runtime environment or 2) some other mod brokenly trying to adjust baits.

I might revisit the baits once I port the mod to Minecraft 1.13 and probably the issue will solve itself in the process. For now, as long as the issue remains super-rare, I'd rather not put out a new release just for a "workaround" that doesn't really solve the issue.

**Comment by Darkmega18** [comment]
Understandable. it hasn't happened anymore, tho mind you the baits only get used early game for acquiring animal drops for EMCing and then become less useful in my pack. Although I do occasionally go crazy with chicken baits for chickens for roost. which is what got me done that time when it went off wrongly, but it didn't do it again with any other baits afterwards.
