### ISSUE TITLE
Compressed Zombie doesn't always split

### ISSUE THREAD

**Issue by darthvader45** [blay09/ExCompressum#241]
I'm using ExCompressum 3.0.17 for 1.12.2, and noticed that occasionally on killing a compressed zombie (using a zombie apocalypse map, so have not tested on compressed skeletons, creepers, etc.), they don't always split into 9 zombies.  Wonder why this happens, or if it was made this way to not be unfair to the player.

On a separate, slightly unrelated note, why no name tag drop anymore?  Is it purely to help with potential lag from spawning so many random zombies?

**Comment by darthvader45** [comment]
Understood, however there were a few that I have killed directly that did not split.  I dealt them the final blow with a sweeping edge 1 Sharpness III diamond sword.  Is the damage caused by a sweep attack technically AoE and thus would not cause the split?  Huh.

**Comment by blay09** [comment]
I checked again and this was a bug after all, compressed mobs currently stop splitting if the world was reloaded after they spawned.

**Comment by darthvader45** [comment]
Yeah, and it might have something to do with AromaBackups as well, not sure
though.

Golden rule in Minecraft: Never dig straight down.
