### ISSUE TITLE
Crash when using a transfer node (Extra Utilities 2)

### ISSUE THREAD

**Issue by maicol07** [blay09/ExCompressum#242]
When I put a transfer pipe (from Extra Utilities 2) behind a machine (like Auto Heavy Sieve) and a transfer node (items) under the machine the game crashes. I have to delete manually with MCEdit the transfer node under the machine to get the world work normally. Can you fix this?
MC version: 1.10.2
Crash log: [latest.log](https://www.pastefile.com/DYHAqL)
Thanks

**Comment by blay09** [comment]
The log is cut off, the actual crash log is missing from it.

**Comment by maicol07** [comment]
Sorry, here is the full one:

[latest.log](https://www.pastefile.com/DYHAqL)

**Comment by blay09** [comment]
```
java.lang.NullPointerException: Ticking block entity
	at exnihiloomnia.registries.crucible.CrucibleRegistry.getItem(CrucibleRegistry.java:85)
	at exnihiloomnia.blocks.crucibles.tileentity.TileEntityCrucible$1.insertItem(TileEntityCrucible.java:49)
	at com.rwtema.extrautils2.itemhandler.InventoryHelper.transferSlotAtoSlotB(InventoryHelper.java:93)
```

The crash happened due to a transfer node trying to insert something into an Ex Nihilo Omnia crucible. This is most likely a bug in Ex Nihilo Omnia and should be reported there.

**Comment by maicol07** [comment]
No, when I deleted the transfer node under the auto heavy sieve it loaded the world

**Comment by maicol07** [comment]
I don't know why it says crucible... test it yourself with Auto Heavy Sieve

**Comment by blay09** [comment]
The crash log is accurate as it shows the exact code sections that lead up to the crash. Nowhere is there any mention of Ex Compressum. Maybe you accidentally connected a crucible without noticing.

Try connecting only the Auto Heavy Sieve with a transfer node in a new world. If you still crash, post the crash log of that, but the log you posted here is completely unrelated to Ex Compressum.

**Comment by maicol07** [comment]
Ok, I'll try it today

**Comment by maicol07** [comment]
I open an issue also in Ex Nihilo Omnia
