### ISSUE TITLE
Modpack use

### ISSUE THREAD

**Issue by xXXIMMATTHEWXXx** [blay09/ExCompressum#246]
Hey, I couldn't find any permission statement earlier.
How can I get permission to use this mod in my modpack? I will gain no money from the pack.

**Comment by blay09** [comment]
See the license: https://github.com/blay09/ExCompressum/blob/1.12/LICENSE

![image](https://user-images.githubusercontent.com/1933180/42732123-4b1132b6-881b-11e8-8830-d7fe87cce253.png)
