### ISSUE TITLE
Configuration question for Heavy Sieve

### ISSUE THREAD

**Issue by AuroraBTH** [blay09/ExCompressum#248]
I'm trying to modify the drops from Compressed Gravel and Compressed Dust. I assumed that the count variable was the one determining how many of that item that dropped.

The following configuration:

```json
{  
    "name":"excompressum:compressed_block",
    "metadata":"*",
    "type":"list",
    "rewards":[  
        {  
            "name": "minecraft:dye",
            "metadata": 15,
            "count": 1,
            "chance": 0.20,
            "luck": 0.0,
            "meshLevel": 1
        }
    ]
}
```

Gives:
![screenshot_4](https://user-images.githubusercontent.com/11875601/43261376-c396aabc-90dc-11e8-8fe0-9cd4ca43fa4e.png)

However, changing "count" to ex. 7 changes it to this:
![screenshot_1](https://user-images.githubusercontent.com/11875601/43261543-5f108ef4-90dd-11e8-96f1-57032eb4a3a0.png)

Shouldn't `*1x` be the one changing to `*7x` and if not, how do one change that value? I'm trying to mimic the original drops, just changing which items that drops (example below).

![screenshot_2](https://user-images.githubusercontent.com/11875601/43261697-f62d4584-90dd-11e8-9fae-1acb44436fb6.png)

Also, what does luck do? I changed it with no visual difference (according to JEI).

---

Also, if possible, a command to dump all current hammer/sieve recipes as JSON would be extremely helpful in understanding how to write your own drop-table as I had no idea meshLevel was a value since it didn't exist in the example file.

**Comment by blay09** [comment]
The count parameter was working as expected (it controls the item count for a drop, not the amount of rolls). But for that purpose, I've added a new "rolls" parameter for rewards that makes what you're trying to do possible without having to duplicate the entry.

Luck is a leftover from earlier versions of Ex Nihilo and is currently not in use. I've removed it from the example file and instead added the newer meshLevel parameter to it.
