### ISSUE TITLE
Hard Crash interaction with NuclearCraft

### ISSUE THREAD

**Issue by remclave** [blay09/ExCompressum#250]
https://pastebin.com/iEtJ0cd1

**Comment by remclave** [comment]
Added: Repeatable. Place NuclearCraft Infinite water source. Placed one Oak Crucible from ExCompressum on one side then placed another on the opposite side. When placing the second crucible is when the game crashes. The game cannot be restarted from the launch menu. Instead the game needs to be restarted from the launch icon.

**Comment by TacticalUniverse** [comment]
https://github.com/turbodiesel4598/NuclearCraft/issues/342 This is what he fixed but seems like more of an issue on ExCompressum end

**Comment by remclave** [comment]
Alright. Closing this issue.
