### ISSUE TITLE
Crushed netherrack not sieving

### ISSUE THREAD

**Issue by bradley21** [blay09/ExCompressum#251]
Mod version 3.0.24

Sieve won't processing crushed netherrack, or the compressed form in the heavy sieve.

Tried all the different meshes, tried manual and auto, as well as various locations.  Auto just tosses the blocks back out.  Manual sieves get to 100% and won't go any further, have to break the sieve to get the block back.

Update
Started working!  Then...stopped all together.  Now does the same thing, for anything dropped into any kind of sieve.  Please fix?  Really enjoying this mod!

**Comment by blay09** [comment]
It's working fine in my tests, try running `/excompressum reload` and see if any errors pop up (or check the log file for anything Ex Nihilo / Ex Compressum related. This sounds like something is wrong with your sieving registry, or a mismatch between client and server sieving registries.
