### ISSUE TITLE
Major FPS drop when sieving continuously!

### ISSUE THREAD

**Issue by RobertLSnead** [blay09/ExCompressum#253]
I have noticed that if you take a whole stack and try to continuously sieve, the FPS starts to drop drastically.
I noticed that the particles below the sieve seem to accumulate and not despawn until you stop sieving.
I even tried to disable all particle effects with optifine to see if maybe it was just a visual, however the issue still happens and affects the entire chunk that the sieve is in.

MC 1.12.2
Mod 3.0.24
ModPack StoneBlock 1.0.14
Optifine Yes/No (Did not matter)
Shaders No

**Comment by RobertLSnead** [comment]
A recommendation would be to keep track of how many particles there are and limit to a number instead of accumulation.  Example limit particles to 100 and start despawning the old and then use the particle.

**Comment by grannymc** [comment]
I'd like to see the mod pay attention to the Particles setting (All - Decreased - Minimal) in the Video Settings. It doesn't appear to be doing so at the moment. Maybe this could be incorporated with Robert's suggestion to set a limit, with a different limit for each settings.
