### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by xNDIZx** [blay09/ExCompressum#254]
Hi Guys, 
I have an issue. When i start the Minecraft Launcher with ExCompressum with the newest Version for 1.7.10 my game keeps crashing. My Ex Nihilo Version is: Ex-Nihilo-1.38-53.jar and my Ex Astris Version is: Ex-Astris-MC1.7.10-1.16-36. Both of these are the newest. What can i do? I want to play Sky Factory 2.4 from the AT Launcher. So i tried to add ExCompressum but it keeps crashing when I start the game.

I would appreciate getting an answer!
xNDIx

**Comment by blay09** [comment]
Make sure Ex Nihilo is on the latest version.

**Comment by xNDIZx** [comment]
Hi

It is, i took the Version: Ex-Nihilo-1.38-53.jar and the ExCompressum
Version: excompressum-mc1.7.10-1.1.149.jar

xNDIZx

Am Mo., 10. Sep. 2018 um 19:45 Uhr schrieb BlayTheNinth <
notifications@github.com>:

**Comment by xNDIZx** [comment]
And it still works not

Am Mo., 10. Sep. 2018 um 20:00 Uhr schrieb NDIPLAYS <avontobel02@gmail.com>:

**Comment by blay09** [comment]
Then post the crash log.

**Comment by xNDIZx** [comment]
[crash-2018-09-10_19.56.56-client.txt](https://github.com/blay09/ExCompressum/files/2367858/crash-2018-09-10_19.56.56-client.txt)

**Comment by blay09** [comment]
Make sure Botania is on the latest version.

**Comment by xNDIZx** [comment]
Now it works! Ty for the Help!
