### ISSUE TITLE
Auto hammer crashes game

### ISSUE THREAD

**Issue by Semichaotic** [blay09/ExCompressum#262]
So i've got an issue when playing on a server getting near to a auto hammer crashes my game

[crash-2018-11-24_22.02.43-client.txt](https://github.com/blay09/ExCompressum/files/2612592/crash-2018-11-24_22.02.43-client.txt)

**Comment by Semichaotic** [comment]
Note: Happenns on newest version too

**Comment by blay09** [comment]
Something must have corrupted the block, I'm adding a workaround that should prevent it from crashing when the inventory NBT breaks.
