### ISSUE TITLE
Support Ex Nihilo Creatios flattenSieveRecipes setting

### ISSUE THREAD

**Issue by EctoOne** [blay09/ExCompressum#272]
Ex Nihilo Creatio has the following option:

> 
        # If enabled, all meshes can obtain the results from the lower tier meshes.
        # Note if the same item is registered in multiple tiers, then the higher tier
        # will have a chance to drop multiples.
        B:flattenSieveRecipes=true

From what I've seen so far, that doesn't apply to Heavy Sieves if the setting is true. Which basically means I have to waste a lot of diamonds for meshes to make the normal sieves efficient enough and then the Heavy Sieves are kinda obsolete.

So, I wish Ex Compressum would adapt that setting, maybe with an config option to enable/disable it.

**Comment by mariodk** [comment]
i can confirm it is also a problem on the normal auto sieve too 

hope you can fix it
