### ISSUE TITLE
Crafttweaker Support?

### ISSUE THREAD

**Issue by mariodk** [blay09/ExCompressum#273]
hey im working on a modpack with this mod included
and when i wanted to change the repice for the auto hammer/sieve & heavy ones
it could only add repice But not remove the existing one via crafting tweaker

so any support for that?

**Comment by blay09** [comment]
Addition and removal of crafting recipes is completely CraftTweaker's domain and does not require any support from this side. Check the CraftTweaker documentation to find the correct way to remove recipes.
