### ISSUE TITLE
Crash when feeding Chorus Fruit to Sieve using Extra Utilities

### ISSUE THREAD

**Issue by Ikarsu** [blay09/ExCompressum#277]
When using a mechanical user from Extra Utilities providing Chorus Fruit to give the Auto Heavy Sieve a speed boost while sifting compressed blocks, it crashes the internal server. 

Under Normal Circumstances, it gives a x4 speed boost for 10 seconds when fed by hand.

ExCompressum Mod version: 1.12.2-3.0.27
Supporting mods: Extra Utilities 1.12-1.9.9
Modpack used for setup: FTB Presents - Stoneblock II

**Comment by blay09** [comment]
Not sure why #271 was closed without comment but this is an issue on Extra Utilities' side.
