### ISSUE TITLE
Server hang/crash with hammer generated mobs

### ISSUE THREAD

**Issue by landonjx** [blay09/ExCompressum#283]
There's no useful crash log for this due to the nature of it.

I have a setup where a mechanical user applies a chicken stick to cobblestone repeatedly. (It's a power-free alternative to the auto hammer.) The chunk is chunk loaded.

The issue comes in when it's left like that for long periods: chunk loaded, no players near enough, constantly using a hammer to break crush-able blocks. The hammer causes chickens to spawn which then suffocate due to newly placed blocks. However, they don't die until there's a player in the vicinity. If there's no players, they seem to just sit there in a dying but not yet dead state. When a player shows up, all the accumulated chickens finishing dieing simultaneously causing the server to hang while trying to resolve the situation. This is a problem if the chunk hasn't had a player in the vicinity in a long time (days) as it can take a while to finish resolving and the watchdog timer will kill the server if a tick lasts longer than one minute.

I'm not sure if this is generally to do with hammer-created mobs or specifically with compressed mobs. I suspect it might have to do more with compressed mobs in this situation.

**Comment by BlayTheNinth** [comment]
That sounds like a problem with the chunkloader mod if mobs are not dieing correctly. Maybe try using a mob killer or something, I don't really see anything I can do about this.
