### ISSUE TITLE
[1.12.2] Compressing modifier ot working with Extrautils compressed sand and gravel

### ISSUE THREAD

**Issue by Felixkeeg** [blay09/ExCompressum#285]
Happened in version 3.0.31

Description:

Issue when using compressing modifier with Tinker's construct tools on Extra Util's compressed blocks:

Compressed cobblestone acts fine.
When using a compressing TiCon's Excavator on compressed gravel, AoE works, but it drops regular sand instead of compressed (this holds true for sand to dust as well)
When using a compressing TiCon's Hammer instead, AoE doesn't work (due to wrong tool), but now it is dropping the compressed variants.

Compressed ExCompressum blocks work fine with the TiCon's Hammer, but are not the default OreDict entry. 

Do you think this issue is due to the way the compressing modifier works, or due to Extra Util's block handling?

A simple fix would be to add the option in the config to make ExCompressum's compressed blocks the higher priority over Extra Util's ones

**Comment by BlayTheNinth** [comment]
Sounds like #99 

Best option is to use a mod like CraftTweaker to force recipes to result in the Ex Compressum blocks instead of the others.
