### ISSUE TITLE
[request] disable everything except for the bait

### ISSUE THREAD

**Issue by kreezxil** [blay09/ExCompressum#288]
I would like an option to disable everything except for the bait, or a new mod that provides just the bait.

for 1.12.2

**Comment by BlayTheNinth** [comment]
Best to just use CraftTweaker to disable the recipes. I might create a bait-only mod, but that would be for 1.15.2+ only.

**Comment by kreezxil** [comment]
1.15.2 is fine, i'll be building a skyblock pack with server this week due
to a mod that provides multiplayer void world management showing up for
1.15.2
