### ISSUE TITLE
Glitch with Optifine and Sphax BDCraft texture

### ISSUE THREAD

**Issue by maicol07** [blay09/ExCompressum#290]
The glass texture is solid and not transparent. See this post for more info about the issue: https://bdcraft.net/community/releases-for-mods-f9/compressum-t5358.html

**Comment by BlayTheNinth** [comment]
OptiFine is not supported. 

The models for the auto sieves are regular Vanilla models with Forge blockstates, so if anything this is probably an issue on OptiFine's side (especially if it only happens with OptiFine installed).

**Comment by maicol07** [comment]
So should I contact the creator of Optifine?
