### ISSUE TITLE
Please Port to 1.15/1.16/1.16.2,  As Ex Nihilo: Sequentia is released 

### ISSUE THREAD

**Issue by BedrockLegends** [blay09/ExCompressum#291]
https://www.curseforge.com/minecraft/mc-mods/ex-nihilo-sequentia/files/3026058

**Comment by Blackout03** [comment]
I hope it does get ported to Sequentia

**Comment by BedrockLegends** [comment]
Mod is now released for 1.16.2 of Ex Nihilo: Sequentia
