### ISSUE TITLE
Game crash with ore smasher in Forever stranded

### ISSUE THREAD

**Issue by bergman0341** [blay09/ExCompressum#296]
While playing Forever Stranded I received a fatal error which crashed the game.  I was using the ore smasher processing some broken and crushed ore from ex nihilio.  crash report shared below.

[crash-2020-11-03_19.38.06-client.txt](https://github.com/blay09/ExCompressum/files/5484879/crash-2020-11-03_19.38.06-client.txt)

**Comment by BlayTheNinth** [comment]
1.10 is no longer supported and future versions no longer have any use for the Ore Smasher at the moment.
