### ISSUE TITLE
Speed Bonus on Sieves might result in performance penalty

### ISSUE THREAD

**Issue by Irgendwer01** [blay09/ExCompressum#300]
Hello, it would be nice if it's possible to add an option to disable the speed bonus on Auto Sieves and Auto Heavy Sieves when clicking with food to reduce the lag on Servers.

**Comment by BlayTheNinth** [comment]
Have you run any performance tests to confirm that the speed bonus is actually causing lag?

**Comment by Irgendwer01** [comment]
@blay09 With Speed Bonus 
![grafik](https://user-images.githubusercontent.com/67506320/108628768-f91a5d80-745c-11eb-9533-99cff0d2bcb5.png)
Without Speed Bonus
![grafik](https://user-images.githubusercontent.com/67506320/108628831-35e65480-745d-11eb-98e5-aa59651c9306.png)
