### ISSUE TITLE
Auto Sieve deletes mesh when sorting

### ISSUE THREAD

**Issue by Pdiddy973** [blay09/ExCompressum#309]
when sorting with a full inventory, the mesh in auto sieve disappears, see gif below
ExCompressum 4.0.2
invi tweaks 1.0.1
Pack ATM6S
![ExCompressum](https://user-images.githubusercontent.com/68764896/111262259-55a30f80-85fa-11eb-9eb3-28c8277c6d7b.gif)

**Comment by corhean** [comment]
I also just experienced this, glad someone already documented it.

**Comment by remplerus** [comment]
[here](https://github.com/reo-ar/InvTweaksRenewed/issues/47)
