### ISSUE TITLE
Allow insertion of food for speed boost

### ISSUE THREAD

**Issue by ghost** [blay09/ExCompressum#310]
it was suggested some time ago that a slot be added to the auto sieves to allow food items (issue #145 )

i'd like to revise this or maybe allow us to hopper/transfer food items into the sieve to apply the speed boost.  Even allowing us to pipe 1 item of food at a time would be nice for automation

just an idea, thank you

**Comment by inspiiree** [comment]
100% would love for this to be a feature :) It's a time saver and also helpful start of game when you need the resources for machines etc.
