### ISSUE TITLE
Crash with AE when attempting to extract hammer from autohammer

### ISSUE THREAD

**Issue by tyler489** [blay09/ExCompressum#313]
Not sure if this is on AE or ExCompressium 

From my report on AE's github
Specifically i had some hammers from excompressium in my AE that i was exporting because they were stuck in the terminal unable to be removed. so i set a fuzzy card to match any and it crashed.

Edit: ok this one is my fault.. I had hammers inside a autohammer from Exconpressium. Excompressium DOES NOT allow you to extract from those slots only insert so when the storage bus "saw" the items and tried to export them into the chest they were unable to be removed. (Not sure if this is on AE for trying to remove items from unremovable slots or on Excompressium for making those slots not able to be extracted from.)

**Comment by BlayTheNinth** [comment]
need crashlog

**Comment by tyler489** [comment]
I was mistaking on the cause and completely forgot to close this. Crash was purely on Ae'2s end their fuzzy card is buggy.
