### ISSUE TITLE
Crash server 

### ISSUE THREAD

**Issue by bigenergy** [blay09/ExCompressum#322]
Crash when breaking foliage with a hook
https://pastebin.com/yM0LKNZm

**Comment by NuclearSpoon** [comment]
I had the same stacktrace and crash. To be specific I was using a compressed crook to break silkworm infested leaves.

**Comment by hyperQ7** [comment]
Same issue. I tested with many tools on the infested leaves and the compressed crook on other items. It's only the compressed crook on infested leaves. I have a modpack with this mod in it and I'm opening a server with it soon. Hopefully it's fixed before then.
