### ISSUE TITLE
Compressed Crook crashes server when harvesting infested leaves

### ISSUE THREAD

**Issue by LWLegends** [blay09/ExCompressum#324]
MCversion: Forge 1.16.5
Mod version: Ex-Compressum_1.16.5-4.0.3.jar
Modpack:  Disunity SkyBlock  https://www.curseforge.com/minecraft/modpacks/disunity-skyblock

BUG: Every time anyone uses a Compressed Crook to harvest Infested Leaves, the Game (both on Server and SMP) crashes instantly.
This has been duplicated on multiple servers and multiple Single player games.

Here is a link to a video showing the crash:
https://www.youtube.com/watch?v=0zOE8L9nW-8(edited)

Here is the crash report:
https://pastebin.com/PjuJ4SNU

**Comment by BlayTheNinth** [comment]
You have to update to [version 4.0.4](https://www.curseforge.com/minecraft/mc-mods/ex-compressum/files/3368007)
