### ISSUE TITLE
[1.16] Bad loottable log

### ISSUE THREAD

**Issue by jinkhya** [blay09/ExCompressum#327]
Hello,
There's something going on with the heavy sieve loottable according to the spam errors I'm getting : 
https://gist.github.com/jinkhya/7b1ec40315a3c17f1c6f378992b0e416

Thanks in advance
Modpack Seaopolis which uses : 

Excompressum 4.0.4
Exnihilo sequentia 20210628182320
forge 36.1.16

**Comment by someaddons** [comment]
You're simply missing a .name("name") on the lootpool builder
