### ISSUE TITLE
An increase in delay caused by automated equipment

### ISSUE THREAD

**Issue by Nqwq** [blay09/ExCompressum#331]
When the mod version excompressum_1.16.5-4.0.4 runs on the server, the use of the automated machines in the mod causes a huge increase in latency for nearby players, up to 20,000 ms, and takes up a lot of server bandwidth, which leads to higher maintenance costs. The server will also be very slow, hope to get the author's solution, thank you very much.### 1.16.5

**Comment by BlayTheNinth** [comment]
I couldn't find any suspicious packet spam, but I've made it so Ugly Steel Plating will now also stop sync packets, so those can be used for places where there's massive amounts of machines.
