### ISSUE TITLE
bug by right click with mods bucket

### ISSUE THREAD

**Issue by GalaxyOfZero** [blay09/ExCompressum#339]
Describe the bug:
when right click with a bucket from the mods Forbidden & Arcanus and Wooden buckets on a wooden crucible, turn into an bucket from Minecraft

To Reproduce

1. Place block ' wooden crucible'
2. Right click on ' Bucket, see describe'
3. Do thing ' turn into Minecraft bucket'

https://github.com/GalaxyOfZero/Skyfriends/issues/1

**Comment by BlayTheNinth** [comment]
Ex Compressum uses Forge's default fluid handler interaction, this is either an issue in Forbidden & Arcanus or Forge

**Comment by GalaxyOfZero** [comment]
i tested it on the new forge version(36.2.19) and it still remains. unfortunately I can not say more
