### ISSUE TITLE
Auto Hammers don't accept netherite hammers

### ISSUE THREAD

**Issue by Graywaren** [blay09/ExCompressum#343]
I'm playing 1.16.5 on a seaopolis modpack and both the compressed and uncompressed auto hammers will not accept their respective netherite hammers. I can't find any config options, tweaks, or anything else that might have interfered with this and the recipes showing their use are still showing in JEI. I can't find any info on whether or not I have to somehow upgrade the machines, but everything I've tried hasn't worked. The netherite hammers are just not accepted. Diamond still works just fine.

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
