### ISSUE TITLE
Client crashed when I add a sieve mesh into auto sieve

### ISSUE THREAD

**Issue by Remering** [blay09/ExCompressum#345]
## Version
Minecraft version: `1.16.5`
Forge version: `36.2.9`
ExCompressum: `4.0.4`
Exnihilo Sequentia: `1.16-20211108-030438`
## Mod pack
[Sky Miners](https://www.curseforge.com/minecraft/modpacks/sky-miners): `1.0.22d`
## Crash report
https://github.com/Remering/pastebins/blob/main/crash-2022-04-17_19.51.43-client.txt

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
