### ISSUE TITLE
Cannot used compressed hammer unless in game mode 1 on Agrarian Skies 2

### ISSUE THREAD

**Issue by Josephur** [blay09/ExCompressum#35]
Not sure if it's Agrarian Skies 2 mods/config that are causing this issue, but we cannot use the hammer unless you are in game mode 1, it simply will not break blocks.  This is very odd as most tools just break blocks when in game mode 1, not work as normal.

I don't know if this is related to AG2's config options that nerf most vanila weapons and others that aren't tinkerers (they are good for recipes only), or a mod conflict?  We would love to fix it for our server though, as it really relieves the tedious hammering task :D

**Comment by blay09** [comment]
See [Troubleshooting](http://balyware.com/index.php/ex-compressum/). Iguana Tinker Tweaks is disabling the tool, you need to adjust the config as mentioned.

**Comment by Josephur** [comment]
Have added this to the server config and restarted it, however the problem persists.

Iguana's config option for S:mods is as follows:

    S:mods <
        RedstoneArsenal
        Thaumcraft
        Botania
        AWWayofTime
        exnihilo
        exastris
        ExtraUtilities
        fluxedcrystals
        Sanguinmancy
        gendustry
        ForbiddenMagic
        WitchingGadgets
        RouterReborn
        excompressum
     >

**Comment by blay09** [comment]
It may need to be set on the clients as well. Anyways, I'm currently making it automatically re-enable the tools and will release it along with the hotfix for #34 in a few minutes, so you might as well wait for that instead.

**Comment by Josephur** [comment]
I will install the hotfix as soon as it's available.    Just so you know I added it client side and that indeed resolved the issue.  Kind of odd, you would think Iguana's would respect the server's config file over the client's any day :/

**Comment by Josephur** [comment]
Your update has resolved the issue, closing.
