### ISSUE TITLE
1.18.2 Wood chippings not dropping

### ISSUE THREAD

**Issue by CritFlaw** [blay09/ExCompressum#359]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

41.1.73

### Mod Version

excompressum-forge-1.18.2-5.0.3

### Describe the Issue

Neither using the Ex Compressum hammer or the Ex Nihilo hammer produces the wood chippings when breaking logs. The JEI recipe also has no seeming recipe. 

### Logs

https://gist.github.com/CritFlaw/3ef0c6d94744edd8f36374b0c7e81ab8

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by JesusFreakTW** [comment]
The same bug appears to apply to the 1.12 version, as well

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
