### ISSUE TITLE
Server crash on 1.7.10 killing compressed pig

### ISSUE THREAD

**Issue by kwpugh** [blay09/ExCompressum#36]
Server crashes when a player kills a compressed pig.

Crash report:  http://pastebin.com/raw/JEcg9G3Q

Using:
- forge-1.7.10-10.13.4.1614-1.7.10-universal.jar
- excompressum-mc1.7.10-1.1.73.jar

**Comment by blay09** [comment]
Update to v1.1.75, it's been fixed already.
