### ISSUE TITLE
Items stuck in auto compressor

### ISSUE THREAD

**Issue by gruniu8** [blay09/ExCompressum#360]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.73

### Mod Version

5.0.3

### Describe the Issue

When everything in the auto compressor gets compressed, the ingredients that are in groups of "not enough" to be compressed are blocking the output of other items by any automated mean (neither modded pipes nor vanilla hoppers work until the ingredients are not there)

### Logs

there's no logs

### Do you use any performance-enhancing mods (e.g. OptiFine)?

no

**Comment by BlayTheNinth** [comment]
This sounds like expected behaviour. What else is it supposed to do?

**Comment by gruniu8** [comment]
just place an auto compressor and a hopper below it, put 5 ore pieces in it. 4 of them will turn into the ore thing and there's still gonna be 1 ore piece that's idk why blocks that ore from going out of that auto compressor

**Comment by BlayTheNinth** [comment]
What version of Balm do you have installed? 3.2.0 fixed some item transfer issues.

**Comment by gruniu8** [comment]
balm-3.2.0+0.jar

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
