### ISSUE TITLE
Auto Compressor requires energy source even when no energy is needed

### ISSUE THREAD

**Issue by Paladin62** [blay09/ExCompressum#361]
I have configured the Auto Compressor to use zero energy but it will not process any items until it is connected to an energy source.

autoCompressorEnergy = 0

When setting the energy cost to zero on the other machines, they are not required to be connected to an energy source to activate.
autoHammerEnergy = 0
autoSieveEnergy = 0

I have tested independently and can see that with the setting the auto compressor does not consume any energy when crafting items.  This issue is that an energy source is required even when no energy is used.

The admin for this server prefers to not add any mod packs that produce energy.

**Comment by BlayTheNinth** [comment]
Please use the [issue template](https://github.com/TwelveIterationMods/ExCompressum/issues/new?assignees=&labels=bug&template=report-a-bug.yml) and ensure all information is present (in particular, the versions used).
