### ISSUE TITLE
1.18.2 Compressed Auto Hammer doesn't gain any speed boost with Netherite Compressed hammer

### ISSUE THREAD

**Issue by wrushton0** [blay09/ExCompressum#362]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.74

### Mod Version

excompressum-forge-1.18.2-5.0.3.jar

### Describe the Issue

When trying to use a compressed netherite hammer within the auto compressed hammer, it accepts it and changes the model to respect this change but gains no speed benefit from it.

### Logs

-

### Do you use any performance-enhancing mods (e.g. OptiFine)?

-

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
