### ISSUE TITLE
[1.18.2] Auto Compressor extraction problem

### ISSUE THREAD

**Issue by mtbrenner** [blay09/ExCompressum#363]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.80

### Mod Version

5.0.3

### Describe the Issue

Automatic extraction from the Auto Compressor does not work.
To reproduce, the following setup is used (top to bottom)
Auto Compressor -> Hopper -> Chest
The Compressor is powered by a creative energy cube from Mekanism.
A stack of diamonds is inserted directly into the compressor's input area
-> The stack is converted to 7 diamond blocks which sit in the output area and 1 diamond remains in the input area. When the lone diamond is taken out of the input area, the diamond blocks are moved to the chest. It seems the output is only emptied when the input area is empty.

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
