### ISSUE TITLE
Log spam - InvocationTargetException

### ISSUE THREAD

**Issue by Officialy** [blay09/ExCompressum#368]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

1.18.2 - 40.1.92

### Mod Version

excompressum-forge-1.18.2-5.0.3.jar

### Describe the Issue

A lot of log spam, https://hastebin.com/opexohiqaq.properties

Something to do with PatchouliAddon Line 13

### Do you use any performance-enhancing mods (e.g. OptiFine)?

Nope

**Comment by BlayTheNinth** [comment]
Will be fixed in 1.20.1 port
