### ISSUE TITLE
Game crashes with Auto-Hammer and Auto-Sieve 1.18.2

### ISSUE THREAD

**Issue by SugarAngel121** [blay09/ExCompressum#369]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.1.68

### Mod Version

5.0.3

### Describe the Issue

The game crashes when placing/accessing the Auto-Hammer and Auto-Sieve; relaunching the game and attempting to load the save with those items placed will result in a crash.

### Logs

https://drive.google.com/file/d/1xy4JqPFVManirxsJEw7kbUNLtLz80aKm/view?usp=share_link

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
Update to Balm 3.2.1

**Comment by SugarAngel121** [comment]
Thank you soo much you saved 2 of my games!!
