### ISSUE TITLE
[1.18.2] Auto Compressor needs a entire rewrite and a lot of fixes

### ISSUE THREAD

**Issue by SimobiSirOP** [blay09/ExCompressum#371]
### Minecraft Version

1.18.x

### Mod Loader

Forge

### Mod Loader Version

40.2.9

### Mod Version

5.0.3

### Describe the Issue

Auto compressor is broken. Input slots are Output slots but nothing can't extract.  Every item transferring pipes that trying to extract from every mod just dupes contents. Hoppers don't work because broken inputs.  Without auto compressor mod lost a lot. Fix the INPUT slots

### Do you use any performance-enhancing mods (e.g. OptiFine)?

No

**Comment by BlayTheNinth** [comment]
Feel free to make a pull request if you know it needs a rewrite. A blanket issue like this without specific reproduction steps for individual issues you encountered is of no use.

**Comment by Chubrel** [comment]
Hoppers work right in 1.20.1, but there are other problems like https://github.com/TwelveIterationMods/ExCompressum/issues/364
