### ISSUE TITLE
Tinker's Construct hammers lose durability in Auto Hammers despite being Unbreakable

### ISSUE THREAD

**Issue by darkmage0707077** [blay09/ExCompressum#375]
### Minecraft Version

Other (specify below)

### Mod Loader

Forge

### Mod Loader Version

Forge 40.2.17

### Mod Version

5.0.3

### Balm Version

3.2.6

### Describe the Issue

![image](https://github.com/TwelveIterationMods/ExCompressum/assets/30854209/31d5d8b1-9fb1-4324-b298-a4e031be3f10)

The Auto Hammer doesn't honor the "Unbreakable" flag from a Tinkers' Construct Nihilo hammer. Looked for a config option to enable it, and it's not present.

While Unbreakable does allow damage from "special sources", I believe that the Auto Hammer using said hammer to do its primary purpose - break blocks down - doesn't count for this.

Minecraft version 1.18.2

**Comment by BlayTheNinth** [comment]
Closing since Tinkers Construct has not updated past 1.19
