### ISSUE TITLE
[1.21] Forge Game Crash in the loading screen

### ISSUE THREAD

**Issue by Periam** [blay09/ExCompressum#377]
### Minecraft Version

1.21

### Mod Loader

Forge

### Mod Loader Version

Forge 51.0.22

### Mod Version

excompressum-forge-1.21-21.0.2.jar

### Balm Version

balm-forge-1.21-21.0.11-all.jar

### Describe the Issue

After installing the mod the game does not launch. with an error/

[crash-2024-07-08_10.41.34-fml.txt](https://github.com/user-attachments/files/16129302/crash-2024-07-08_10.41.34-fml.txt)

### Do you use any performance-enhancing mods (e.g. OptiFine) or custom server distributions (e.g. SpongeForge)?

no

**Comment by BlayTheNinth** [comment]
Fixed in Balm 21.0.12
