### ISSUE TITLE
Do you planned an 1.19 Forge update?

### ISSUE THREAD

**Issue by Mat1212fr** [blay09/ExCompressum#382]
I love Ex Nihilo and for some reasons I launched a new game on a ne modpack in 1.19.2.

I was surprised that the whole 1.19.X have been skipped and it is why I ask do you planned on a 1.19 update? Or do you think that a true beginner as me can modify the code to make it work on this version?

Thanks you a lot for this very helpful mod!

**Comment by Mat1212fr** [comment]
Ok,
For those who thought that modifying the mods.toml would work you'll receive this error for 1.18.2-5.0.3: (be aware I'm not programmer, so perhaps I did something wrong)
```
-- MOD excompressum --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/client/model/data/IModelData 
```
And backward, 1.20.1-20.1.6:
```
-- MOD excompressum --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraft/world/level/storage/loot/LootDataResolver
```
I knew it would probably do that but I wanted to try

Entirely waiting for dev answer now! ❤️‍🔥

**Comment by BlayTheNinth** [comment]
There are no plans to backport Ex Compressum to 1.19 or other skipped versions and it is not a trivial task.
