### ISSUE TITLE
The Crucible ate my leaves T_T

### ISSUE THREAD

**Issue by blay09** [blay09/ExCompressum#41]

**Comment by tifkat** [comment]
Dude, I don't know if I should make my bug report or not. What was this bug/fix? I want to automate leaves -> crucible with chest/hopper. Crucible is eating the leaves up when there are less than 1000mB worth of leave in it (effectively getting 8mB per leaf block.) Skyfactory 3, 3.0.14, Ex-Compressum 1.10.2-2.0.97

Extra Utilities Transfer node (liquid) connected, transferring water to an oak barrel, for clay automation.
