### ISSUE TITLE
automation

### ISSUE THREAD

**Issue by Manuepolis23** [blay09/ExCompressum#5]
can you add an automatic sieve like the one from ex astris?

**Comment by blay09** [comment]
Why don't you just use Ex Astris?

**Comment by Manuepolis23** [comment]
compressed blocks don't work in that sieve

**Comment by blay09** [comment]
That's the point. Compressed Block sieving is meant to be manual only. If you really want to automate it, set Allow Heavy Sieve Automation to true in the config file and set up auto-clicking of a heavy sieve using an autonomous activator or something.

**Comment by Manuepolis23** [comment]
Ok ,I understand.

**Comment by Manuepolis23** [comment]
There is a way to copy all the recipes from heavy sieve to the automatic sieve?

**Comment by blay09** [comment]
You can write a MineTweaker + ModTweaker script to add compressed blocks to the normal/automatic sieve.
