### ISSUE TITLE
Passive Auto Sieve Buff through Beacons?

### ISSUE THREAD

**Issue by blay09** [blay09/ExCompressum#53]

**Comment by muaddib912** [comment]
Eliminates book enchantment decay through the use of beacons?

**Comment by blay09** [comment]
This was a random idea I was given that Beacons should work as a replacement for enchanted books (mainly Speed). I'm not sure though, since there's no Fortune on Beacons and it the implementation is probably not worth it.

**Comment by NdMSnIpEz** [comment]
Possibly make it so the buff normally applied by food can be applied to the sieve when an active beacon is nearby?
