### ISSUE TITLE
Enchantes books cand be placed

### ISSUE THREAD

**Issue by Manuepolis23** [blay09/ExCompressum#56]

**Comment by blay09** [comment]
This was fixed in v1.1.88.

**Comment by Manuepolis23** [comment]
is still not fixed for my setup

**Comment by blay09** [comment]
What are they enchanted with? It only accepts Fortune and Efficiency.

**Comment by Manuepolis23** [comment]
This only 2.and separately. I used ender io enchanter

**Comment by kurokuno** [comment]
same issue with disenchanter from draconic version 1.1.93
