### ISSUE TITLE
Crash while attempting to load game

### ISSUE THREAD

**Issue by Azanorashit** [blay09/ExCompressum#60]
Ex nihilo is as updated as it can be, does ex compressum require shitania or something?
http://pastebin.com/FhiXWHt1

**Comment by blay09** [comment]
Never heard of that "Shitania" mod. I assume you're an angry person talking about Botania. And no, I don't know how you would come to that conclusion, as the first relevant line clearly states it's failing at loading the RF Auto Heavy Sieve. Not related to Botania at all.

I missed a line and therefore the latest CurseForge build has a hard dependency on CoFH Core.
The latest build [here](http://jenkins.blay09.net/job/Ex%20Compressum/) should fix your issue.

Protip for the future: keep your mod-hate to yourself, it makes you look silly.

**Comment by Azanorashit** [comment]
I asked because when I was trying to figure out the problem, youre own site said two things relating to the first line in the error, one being ex nihilo and the other being botania. 

So I need to install cofh core? Cause it crashed again.
http://pastebin.com/8fFcyqC8

**Comment by blay09** [comment]
Humph, I'm bad at this. Yes, installing CoFH Core would work as a workaround for now. I'll need to look into how to make the RF API optional properly.

**Comment by Azanorashit** [comment]
Why make cofh core a dependency in the first place? Just the rf api?

**Comment by blay09** [comment]
Yes. It's not supposed to be a dependency. The items are supposed to just not get loaded if CoFH Core isn't available, but the class is still getting loaded as it's referenced, causing the crash. I may have to ship the RF API within Ex Compressum to solve the issue.

**Comment by Azanorashit** [comment]
Well at least you understand what the problem is, thats more than I can say about most modders.
