### ISSUE TITLE
Crash when placing Extra Util transfer pipe on top of an oak crucible

### ISSUE THREAD

**Issue by CarlLusty** [blay09/ExCompressum#67]
Playing with FTB Infinity Evolved Skyblock 1.02.
The jar they use is: excompressum-mc1.7.10-1.1.95.jar
I assume that means V1.1.95
I've tried it again in a new single player skyblock 1.02 world, same thing happened.

java.lang.IllegalArgumentException: Cannot create a fluidstack from a null fluid
3541         at net.minecraftforge.fluids.FluidStack.<init>(FluidStack.java:36)
3542         at net.blay09.mods.excompressum.tile.TileEntityWoodenCrucible.getTankInfo(TileEntityWoodenCrucible.java:163)
3543         at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:82)
3544         at com.rwtema.extrautils.tileentity.transfernodes.TNHelper.isValidTileEntity(TNHelper.java:64)
3545         at com.rwtema.extrautils.tileentity.transfernodes.pipes.PipeBase.shouldConnectToTile(PipeBase.java:79)
3546         at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getPipeModel(BlockTransferPipe.java:223)
3547         at com.rwtema.extrautils.tileentity.transfernodes.BlockTransferPipe.getWorldModel(BlockTransferPipe.java:193)
3548         at com.rwtema.extrautils.block.BlockMultiBlockSelection.func_149731_a(BlockMultiBlockSelection.java:19)
3549         at net.minecraft.world.World.func_147447_a(World.java:1221)
3550         at net.minecraft.world.World.func_72901_a(World.java:1029)

**Comment by blay09** [comment]
Oh hey, this is probably the "null error liquids I think saplings to create water" issue that other person has failed to report in a comprehensible manner.

Fix will be up later today. :)
