### ISSUE TITLE
Auto Compressor doesn't accept dust

### ISSUE THREAD

**Issue by tobino93** [blay09/ExCompressum#68]
In version 1.1.95 the auto compressor does not accept the dust as input, neither manually or with some pipes.

Find out on FTB Infinity Expert Skyblock 1.0.4.

**Comment by NdMSnIpEz** [comment]
Try updating manually to the 1.1.99 release from the FTB launcher and try to reproduce.

**Comment by blay09** [comment]
Yeah, it didn't make it into the latest Infinity hotfix sadly. Updating Ex Compressum manually will fix the issue.
