### ISSUE TITLE
Enchanted books don't work well

### ISSUE THREAD

**Issue by Manuepolis23** [blay09/ExCompressum#69]
The enchanted books from creative tab and that from ender io enchanter don't do nothing.if you enchant an enchanted book with the x thing from NEI it works as it should

**Comment by Manuepolis23** [comment]
The tags are different.from the nei thing is ench and from creative tab is enchantmen

**Comment by Manuepolis23** [comment]
Enchantment * :)

**Comment by blay09** [comment]
Are you sure this is on the latest version? Because it should be the other way around.

**Comment by Manuepolis23** [comment]
Just tested and the bug still exists in the latest build.

**Comment by blay09** [comment]
#75
