### ISSUE TITLE
Auto Heavy Sieve doesn't go faster when boosted?

### ISSUE THREAD

**Issue by ScorpioRage** [blay09/ExCompressum#71]
Seems as though when using the Chicken Stick to try and break any of the ore (gravel, sand dust), it doesn't hammer them into the next tier, it only breaks the block. IE: Trying to break a Iron Ore Gravel, instead of getting 4-5 Crushed Iron Ore, you get the gravel back.

With the Auto Heavy Sieve, when giving the sieve slaves food, the actual sieving speed doesn't increase but the animation speeds up, and in the HUD it displays what the speed boost should be. A normal Auto Sieve fed Beef Wellington actually out produces a Auto Heavy because of this. Also tried different foods comparing two Heavy Sieves, and the speeds are the same.

**Comment by blay09** [comment]
1. is intended, it's only meant to break down non-ore blocks.

I'll have a look into 2.
