### ISSUE TITLE
Make NEI enchanted books work as well

### ISSUE THREAD

**Issue by blay09** [blay09/ExCompressum#75]
So people can stop reporting it as a bug on my side.

**Comment by Manuepolis23** [comment]
I tested and it is not working :(

**Comment by blay09** [comment]
I don't know *what* you are doing but you're doing it wrong. It's confirmed to be working with both normally enchanted books and books enchanted through NEI in version 109+.

**Comment by Manuepolis23** [comment]
I will try in a new instance

**Comment by Manuepolis23** [comment]
http://imgur.com/a/PH4zY
proof

**Comment by blay09** [comment]
I see now. I confused the issue with the one that wouldn't let you place a book in the slot at all.

**Comment by Manuepolis23** [comment]
Now it really works.thanks a lot.you are an awesome person.
