### ISSUE TITLE
Insertion & Extraction of Enchanted Books into Auto Sieve

### ISSUE THREAD

**Issue by Manuepolis23** [blay09/ExCompressum#79]
Is there any way to extract the books from enchanted books slot in auto sieves?

**Comment by blay09** [comment]
I don't think there is at this point, but I can see why people would need it. The best way to implement this is probably by letting people choose a side for Book I/O themselves, so older setups aren't broken and people aren't limited to only extract from the bottom, for example.

I'll look into it.
