### ISSUE TITLE
Ore smasher shouldn't place dusts

### ISSUE THREAD

**Issue by Iamtk421** [blay09/ExCompressum#81]
The ore smasher, while useful, shouldn't craft and place dust as it can't be 'smashed' further, and certainly shouldn't when gravel/sand variations are available to be processed. Doing so just wastes durability on the tool if it's used to mine the dust.

It will also place pre-existing block form dust (if they're earlier in the inventory), when it has broken 'gravel' ores it can craft and place instead.

**Comment by blay09** [comment]
This was fixed in v109+

#66

**Comment by Iamtk421** [comment]
Okay, cool.
I checked open and closed issues but didn't check the commit history to see if it had been fixed.
