### ISSUE TITLE
Auto Compressor: Option to always keep one item in input slot

### ISSUE THREAD

**Issue by Zaflis** [blay09/ExCompressum#87]
Would like a config or default option that it would always keep 1 in inventory. So for example it would wait to get 10 redstone dust before making a block.

**Comment by blay09** [comment]
What's wrong with just using filters on your input?

**Comment by Zaflis** [comment]
Itemduct is the only pipe i know that has 12 slots for filter. EnderIO Item conduits limit to 5 and 10 for high tier expensive recipe. Extra Utilities would need a retrieval node for each compressor, but is much more expensive QED recipe, and would need a filter inside filter to reach 12.

And even though rare, it's possible that 2 of same items occupy 2 slots inside the machine. Say it's processing tin dust, and in the meantime it receives 65 redstone. If it starts from fuller stack, it would leave 2 stacks of 1 + 1 redstone.

RFTools crafter also can keep 1 item always remaining, but in addition it can filter inventory slots for materials. It makes operating the machine easier and more reliable.

**Comment by blay09** [comment]
The upcoming 1.12 version adds a rationing auto compressor that will always leave one item behind.
