### ISSUE TITLE
Suggestion Redstone Control

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/ExCompressum#90]
Redstone control for machines. in example:
Comparator support to get how full the output is.
Redstone to turn the machines on and off.
Please Senpai T.T

**Comment by blay09** [comment]
Added Comparator support. Redstone support could break existing setups so I'd have to make it opt-in, which is too much work to justify for 1.7.10 :(

**Comment by blay09** [comment]
The upcoming 1.12 version adds redstone control to the Auto Sieves, Auto Hammers and Auto Compressor.
