### ISSUE TITLE
Machinist's Workbench can't craft Compressed Hammers

### ISSUE THREAD

**Issue by Zero9o1o** [blay09/ExCompressum#91]
Tried to make a compressed stone hammer and all it did was do the repair recipe and eat all nine hammer to make 1 normal hammer.
![alt tag](https://i.gyazo.com/c9a0232310f287366a4e3350072bf4b3.png)

**Comment by Zero9o1o** [comment]
I don't know if this is an issue on thermal expansions end or not.

**Comment by blay09** [comment]
That's an issue in Thermal Expansion.
