### ISSUE TITLE
Compressed mobs "explode" out of grinders on death.

### ISSUE THREAD

**Issue by NolanSyKinsley** [blay09/ExCompressum#92]
I am currently having an issue with a basic drop grinder where the compressed mobs spawn the 9 mobs outside the grinder when they die. It is a 3x3 area so they shouldn't be phasing through the walls at all, but I have 1/2 block at the bottom open and I think this may be what is allowing them out.

**Comment by blay09** [comment]
[Compressed mobs will only be uncompressed when killed by a (real) player.](https://github.com/blay09/ExCompressum/blob/master/src/main/java/net/blay09/mods/excompressum/handler/CompressedEnemyHandler.java#L48) Are you sure it's compressed mobs that are uncompressing which is causing the issue?

**Comment by NolanSyKinsley** [comment]
Yes, my grinder is a drop grinder, I am killing them manually.

**Comment by blay09** [comment]
Hm. Things glitching through walls must be an issue with Vanilla though. The uncompressed mobs are spawned in the same position as the source and get random motion applied to them.

I have a similar setup (except the mobs are standing on full blocks for me) and I've not had any of them escaping. I'm not sure what to do to fix this. You could lower the amount they uncompress into to four or something and see if that helps, or alternatively just disable them completely in the config file.

**Comment by NolanSyKinsley** [comment]
For now I have disabled the more dangerous ones. Although it was a bit laggy, I  did notice that they didn't seem to spawn at the exact position of the death of the mobs, it was more around the position of the head at the end of the death animation. That is pure speculation, and I feel it may have to do with either the corners of the grinder or the game engine not wanting to spawn 9 mobs on the same spot so it spreads them out some and that causes them to be spawned outside.
