### ISSUE TITLE
Double Compressed Diamond Hammer TiCon upgrade issues

### ISSUE THREAD

**Issue by MikrySoft** [blay09/ExCompressum#99]
The Smashing II upgrade doesn't work terribly well for compressed gravel and sand. 
WAILA says that correct tool for all compressed blocks is pickaxe, so I would assume that at least hammer would work, but to be sure I have made both a hammer and an excavator, then upgraded them with double compressed diamond hammers. 
While breaking compressed cobble (with the hammer) works as expected, compressed gravel and sand are both having issues:
- Breaking with hammer breaks in 3x3, but has speed equal to breaking by hand. Tool XP is awarded properly.
  Increasing the speed of the hammer (to absurd ~26, magical wood tools rule) doesn't influence the breaking speed.
- Breaking with excavator has correct speed for the tool, but doesn't break in 3x3 pattern.  Tool doesn't get more XP (as expected for an incorrect tool for the job).

Tested with latest (1.1.131) version inserted into latest Infinity Skyblock.

**Comment by blay09** [comment]
I think this is an issue between Tinkers and Extra Utilities' Compressed Blocks. Have you tried the same with a normal diamond hammer upgrade (added by Ex Astris)?

**Comment by MikrySoft** [comment]
ExAstris hammers work as expected:

- hammer on a hammer quickly breaks 3x3 of cobble into gravel, works slowly on gravel/sand and does 1x1 only.
- hammer on an excavator quickly breaks 3x3 of gravel/sand, works slowly on cobble in 1x1 only (as if breaking by hand)

Quick test shows that the incorrect behavior (hammer has 3x3 but no speed, excavator has speed but not 3x3) happens also without adding hammers, so that's on @RWTema. It looks like somehow somewhere isEffective check fails, but I don't understand why it would do so, unless some intentional magic happens.

**Comment by blay09** [comment]
Does this issue persist in 1.10.2?

**Comment by MikrySoft** [comment]
1.10.2 status (tested in SF3)
 - ExCompressum compressed cobble, gravel and sand all work fine with a hammer.
 - Extra Utilities 2 single compressed cobble works fine with a hammer
 - Extra Utilities 2 single compressed gravel and sand work fine, but require an excavator instead. Hammer breaks blocks with a correct speed, but only in 1x1 and without dropping anything.
 - Extra Utilities 2 double compressed cobble breaks fast and in 3x3, but doesn't drop anything

**Comment by blay09** [comment]
Thanks. Unfortunately there doesn't seem to be a way to make a modifier change a tool in a way that allows it to harvest other block materials as it's [hardcoded](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/tools/tools/Pickaxe.java#L56-L59) to a call [with no modifier callbacks](https://github.com/SlimeKnights/TinkersConstruct/blob/master/src/main/java/slimeknights/tconstruct/library/tools/ToolCore.java#L181-L184) at the moment.

**Comment by MikrySoft** [comment]
Anything on the double compressed cobble not dropping anything?

**Comment by blay09** [comment]
Not dropping will be fixed in the next version.

As for the hammer issue, adding Tinker's blasting modifier to your tool will allow it to hammer gravel and sand, and starting next version should still always result in a drop (rather than destroying the output by chance as it normally does).
